language: go
sudo: false

matrix:
  include:
    - go: tip

install:
  - dep ensure
  
script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v ./...
  - overalls -project=github.com/sharonjl/sqsx  -covermode=count
  - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken=$COVERALLS_TOKEN
